### ISSUE TITLE
500, No query method provided error

### ISSUE THREAD

**Issue by i-like-robots** [Netflix/falcor-express#28]
This response is implemented here: https://github.com/Netflix/falcor-express/blob/master/src/index.js#L19-L21

But [`requestToContext`](https://github.com/Netflix/falcor-express/blob/master/src/requestToContext.js#L13) currently never sets a `method` property.

**Comment by Autarc** [comment]
The method for the falcor route will be provided as a query param of the request and sent along the selected path (e.g. `&method=get`). As its not mentioned in the documentation or the shown examples I am aware it can be misleading. Could perhaps be added for people who like to check the results directly in the browser.
